apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
  labels:
    app: vue-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue-frontend
          image: wanderleyfl/naturaleza-app:latest   # CircleCI lo empuja
          ports:
            - containerPort: 80